apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:RlMmIjddpNav7h/TDCcMVGCgnspOnKts8TqMjA0bx5vmCzXt75W2C7Lpwni/erc0VY/PaPk=,iv:Pi5k4D8iEtjrpHcK6cj7Zcnr4DvVrdAFw6+zUmrJY0k=,tag:9GYWuHJTZ1sYIh8vt45U4Q==,type:str]
sops:
    age:
        - recipient: age1dwvrsd7g7mnc80cgjwnxygyf8j5gwxffr45mxqvuf60kmm6vtpvqm4lkwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UkZ4UTJ0OVZ6eml4bmpL
            ZXgwdjRzSkdqVFRoOFlrNEkxREoxZkppdGpBCnBIV3I0b2pxbUhUVWZIWEZwYWp5
            RVV3aUg5YVI3M2xkMEV2LytuQmRmOFUKLS0tIGR5ZzR2NTRrdTllcmhyL0wyMk5r
            OFNzTlVaZ29KM2wwQ3lxd1cwNXNIVGMK1y2p7XVqba4icCVWCK6N/c4h9mUsFKB6
            KzqN/WhFvB6W2e5Ru2J3kKve4wHE1j9FaYXV1NJPUyN0uQ6HuxBCmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T12:09:44Z"
    mac: ENC[AES256_GCM,data:m9ObqCgxmdY9hzVyVZjTkF3OlvWgqLmOb/9qkgcJr1Mcsb3uBbjQ2tP1D3vVN3Eptc/5UijbU+1a/b0Li7OIsNXyi6ve3+1+OrH2vSWEoCGcw7tVcWJ5PEa0ikwM3qW/pNOYJ/l+f6EJ5iHQVMCpwujLCjnwx7cDXSzXOcvcMtg=,iv:F2IKYDNMJNwb3ErdZJXPSY6PhSbn+0FM2qxS9bdAvLk=,tag:zUIqvSetzPWHlUHtbSnLpw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:7FO1vG/eRGLAfA/GEYBY/fanwYsRusR8zWOw6YMaflrKHvzSBVfmt4hr0IvyCvARt4jFNN0=,iv:R0vK3LkCmcw86CPR/XxB2+V2tZpyA8sRe/WCPRYBhGE=,tag:7MkhFXEDJeb/ztS5AEtkdA==,type:str]
sops:
    age:
        - recipient: age1dwvrsd7g7mnc80cgjwnxygyf8j5gwxffr45mxqvuf60kmm6vtpvqm4lkwa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UkZ4UTJ0OVZ6eml4bmpL
            ZXgwdjRzSkdqVFRoOFlrNEkxREoxZkppdGpBCnBIV3I0b2pxbUhUVWZIWEZwYWp5
            RVV3aUg5YVI3M2xkMEV2LytuQmRmOFUKLS0tIGR5ZzR2NTRrdTllcmhyL0wyMk5r
            OFNzTlVaZ29KM2wwQ3lxd1cwNXNIVGMK1y2p7XVqba4icCVWCK6N/c4h9mUsFKB6
            KzqN/WhFvB6W2e5Ru2J3kKve4wHE1j9FaYXV1NJPUyN0uQ6HuxBCmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T12:09:44Z"
    mac: ENC[AES256_GCM,data:m9ObqCgxmdY9hzVyVZjTkF3OlvWgqLmOb/9qkgcJr1Mcsb3uBbjQ2tP1D3vVN3Eptc/5UijbU+1a/b0Li7OIsNXyi6ve3+1+OrH2vSWEoCGcw7tVcWJ5PEa0ikwM3qW/pNOYJ/l+f6EJ5iHQVMCpwujLCjnwx7cDXSzXOcvcMtg=,iv:F2IKYDNMJNwb3ErdZJXPSY6PhSbn+0FM2qxS9bdAvLk=,tag:zUIqvSetzPWHlUHtbSnLpw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
