apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - cloudflare.sops.yaml
  - cert-manager.yaml
  - proxmox-csi.yaml
  - csi-driver-nfs.yaml
  - ingress-nginx.yaml
  - cloudflared.yaml
  - external-dns.yaml
  - actions-runner-controller.yaml
  - arc-runner-pat.sops.yaml
