apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - cloudflare.sops.yaml
  - cert-manager.yaml
  - proxmox-csi.yaml
  - ingress-nginx.yaml
  - cloudflared.yaml
