apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Home
    theme: dark
    color: slate
  widgets.yaml: |
    - search:
        provider: duckduckgo
        target: _blank
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
  services.yaml: |
    []
  bookmarks.yaml: |
    []
