apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wattbill
components:
  - ../../components/restrict-http-to-ingress-nginx
resources:
  - namespace.yaml
  - ghcr-pull.sops.yaml
  - deployment.yaml
  - ingress-internal.yaml
  - ingress-public.yaml
