apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - deployment.yaml
  - ingress-internal.yaml
  # - ingress-public.yaml   # enabled after backup restore (see abs-expose step)
